### PR TITLE
folder structure created

### PR DESCRIPTION
**Pull request by Vinita686**
folder structure created

### CODE REVIEW

**Review by zamanpour — CHANGES_REQUESTED** [review]
Please check the folders

**Review by xiaozhao1111 — CHANGES_REQUESTED** [review]
The js folder is in the css folder.

**Review by zamanpour — APPROVED** [review]
Great!
But I cannot find the images folder

**Comment by xiaozhao1111** [comment]
ok

**Review by xiaozhao1111 — APPROVED** [review]
ok

**Pull request merged**
